# Generated by Django 3.0.14 on 2022-01-02 01:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ],
        ),
        migrations.CreateModel(
            name='UserVideoJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_junctions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_junctions', to='video_recommendations.Video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
