# Generated by Django 3.0.14 on 2022-01-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20211203_1955'),
        ('video_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='associated_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
