# Generated by Django 3.0.14 on 2022-01-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_recommendations', '0002_auto_20220108_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
