# Generated by Django 3.0.14 on 2022-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20211203_1955'),
        ('video_recommendations', '0003_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='associated_category',
        ),
        migrations.AddField(
            model_name='video',
            name='associated_categories',
            field=models.ManyToManyField(to='course.QuestionCategory'),
        ),
    ]
