# Generated by Django 3.0.14 on 2022-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_recommendations', '0004_auto_20220118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
